//! `trousseau man` (3.5.17).

use clap::CommandFactory as _;
use clap_mangen::Man;

use crate::cli::{Cli, ManArgs};

/// Run `man`: print the roff man page for the top-level command,
/// generated by `clap_mangen` from the same [`Cli`] tree `cli.rs`
/// declares, or for `args.subcommand` if one is given, to stdout.
///
/// # Errors
///
/// Returns an error if `args.subcommand` is given but does not name a
/// known subcommand, or if stdout cannot be written to.
pub fn run(args: &ManArgs) -> anyhow::Result<()> {
    let command = Cli::command();
    let man = match &args.subcommand {
        None => Man::new(command),
        Some(name) => {
            let subcommand = command
                .find_subcommand(name)
                .cloned()
                .ok_or_else(|| anyhow::anyhow!("no such subcommand: {name}"))?;
            Man::new(subcommand).title(format!("trousseau-{name}"))
        }
    };
    let mut stdout = crate::output::writer();
    man.render(&mut stdout)?;
    Ok(())
}
