name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    name: Release
    runs-on: macos-latest
    permissions:
      contents: write # for goreleaser to create the release
      id-token: write # for actions/attest-build-provenance
      attestations: write # for actions/attest-build-provenance
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install stable toolchain for x86_64 linux
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          cache: false

      - name: Install stable toolchain for aarch64 linux
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          cache: false

      - name: Install stable toolchain for x86_64 macOS
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          cache: false

      - name: Install stable toolchain for aarch64 macOS
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          cache: false

      - name: Setup zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          use-cache: false

      - name: Install cargo-zigbuild
        run: cargo install --locked cargo-zigbuild

      - name: Install cargo-cyclonedx
        run: cargo install --locked cargo-cyclonedx

      - name: Install just
        run: brew install just

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config=.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: |
            dist/*.tar.gz
            dist/*.deb
            dist/*.apk
            dist/checksums.txt
